#!/bin/bash
set -e

# Create non-root user for n8n
NON_ROOT_USER="${POSTGRES_NON_ROOT_USER}"
NON_ROOT_PASSWORD="${POSTGRES_NON_ROOT_PASSWORD}"
N8N_DB="${POSTGRES_DB}"

# Create non-root user
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$N8N_DB" <<-EOSQL
  CREATE USER "$NON_ROOT_USER" WITH PASSWORD '$NON_ROOT_PASSWORD';
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "$NON_ROOT_USER";
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "$NON_ROOT_USER";
  ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO "$NON_ROOT_USER";
  GRANT ALL PRIVILEGES ON DATABASE "$N8N_DB" TO "$NON_ROOT_USER";
  GRANT ALL PRIVILEGES ON SCHEMA public TO "$NON_ROOT_USER";
  ALTER SCHEMA public OWNER TO "$NON_ROOT_USER";
EOSQL

echo "PostgreSQL initialization completed successfully"
